import { z } from 'zod'

export const booleanField = z.boolean().nullable().default(null)
export const scaleField = z.number().min(0).max(10).default(0)
export const numberField = z.number().default(0)

export const protocolDataSchema = z.record(
  z.string(),
  z.union([z.boolean(), z.number(), z.string()])
)

export const shoulderDataSchema = z.object({
  pgmPresent: booleanField,
  painType: z.string().default(''),
  eva: scaleField,
  branchGeneralNeural: booleanField,
  branchCannotRaise: booleanField,
  branchPointPain: booleanField,
  bilateralPain: booleanField,
  gaitDeviation: booleanField,
  hoffmanTest: booleanField,
  invertedSupinator: booleanField,
  babinskiTest: booleanField,
  over45: booleanField,
  myelopathyPositive: booleanField,
  ulnt1Median: booleanField,
  romRotationLess60: booleanField,
  distractionTest: booleanField,
  compressionTest: booleanField,
  spurlingTest: booleanField,
  wainnerPositive: booleanField,
  sensibilityAffected: booleanField,
  strengthAffected: booleanField,
  reflexAffected: booleanField,
  conductionAffected: booleanField,
  roosTest: booleanField,
  adsonTest: booleanField,
  edenTest: booleanField,
  morleyTest: booleanField,
  wrightTest: booleanField,
  costoclavicularTest: booleanField,
  tinelTest: booleanField,
  tosPositive: booleanField,
  cervicalPAMovementPain: booleanField,
  medianNerveTest: booleanField,
  medianInterfaceTest: booleanField,
  medianPalpation: booleanField,
  ulnarNerveTest: booleanField,
  ulnarInterfaceTest: booleanField,
  ulnarPalpation: booleanField,
  flexionElbowTest: booleanField,
  radialNerveTest: booleanField,
  radialInterfaceTest: booleanField,
  radialPalpation: booleanField,
  activePain: booleanField,
  passivePain: booleanField,
  externalRotationPainful: booleanField,
  frozenLess50ExternalRotation: booleanField,
  frozenLess30ExternalRotation: booleanField,
  frozenPainForcedER: booleanField,
  frozenLessHorizontalAdduction: booleanField,
  frozenLessInternalRotation: booleanField,
  frozenLessFlexion: booleanField,
  coracoidPainTest: booleanField,
  age60Plus: booleanField,
  passiveAbductionPainful: booleanField,
  spontaneousStrongPain: booleanField,
  noImprovementRecentrage: booleanField,
  dropArmSign: booleanField,
  supraspinatusStrengthTest: booleanField,
  lateralRotationLagSign: booleanField,
  infraspinatus: booleanField,
  internalRotationLagSign: booleanField,
  mobilityImprovesWithScapula: booleanField,
  muscleAtrophy: booleanField,
  scapularAssistanceTest: booleanField,
  scapularRetractionTest: booleanField,
  isrt: booleanField,
  sdtFlexionAffected: z.string().default('NORMAL'),
  sdtAbductionAffected: z.string().default('NORMAL'),
  apprehension: booleanField,
  apprehensionAnterior: booleanField,
  relocationTest: booleanField,
  surpriseTest: booleanField,
  sulcusSign: booleanField,
  gageyTest: booleanField,
  jerkTest: booleanField,
  posteriorImpingement: booleanField,
  instabilityTUBS: booleanField,
  instabilityAMBRI: booleanField,
  instabilityAIOS: booleanField,
  acLineTenderness: booleanField,
  acCrossbodyAdduction: booleanField,
  acResistedExtension: booleanField,
  acOBrien: booleanField,
  acPaxino: booleanField,
  acHawkins: booleanField,
  acTraumatic: booleanField,
  acKeySign: booleanField,
  neerTest: booleanField,
  hawkinsKennedy: booleanField,
  painfulArcSign: booleanField,
  abdHorizontalPainful: booleanField,
  crankTest: booleanField,
  anteriorSlideTest: booleanField,
  obrienTest: booleanField,
  compressionRotationTest: booleanField,
  dynamicLabralShearTest: booleanField,
  passiveCompressionTest: booleanField,
  yergasonTest: booleanField,
  bicepsLoadTest: booleanField,
  passiveDistractionTest: booleanField,
  supraspinatusNeuropathy: booleanField,
  axillaryNeuropathy: booleanField,
  psychosocialFactors: booleanField,
})

export const cervicalDataSchema = z.object({
  eva: scaleField,
  sintomasNeurologicos: booleanField,
  dolorIrradiadoBrazo: booleanField,
  cefalea: booleanField,
  traumatismoLatigazo: booleanField,
  dolorLocalCervical: booleanField,
  desviacionMarcha: booleanField,
  hoffmanTest: booleanField,
  supinadorInvertido: booleanField,
  babinskiTest: booleanField,
  mayorDe45: booleanField,
  ulnt1: booleanField,
  romRotacionMenor60: booleanField,
  testDistraccion: booleanField,
  spurlingTest: booleanField,
  testFlexionRotacion: booleanField,
  dolorUnilateralCabeza: booleanField,
  dolorReproduceMovCervical: booleanField,
  limitacionFlexion: booleanField,
  limitacionExtension: booleanField,
  limitacionRotacionDerecha: booleanField,
  limitacionRotacionIzquierda: booleanField,
  limitacionInclinacionDerecha: booleanField,
  limitacionInclinacionIzquierda: booleanField,
  patronHomolateral: booleanField,
  patronContralateral: booleanField,
  testRoos: booleanField,
  testAdson: booleanField,
  edenTest: booleanField,
  morleyTest: booleanField,
  mejoraManipulacionToracica: booleanField,
  mejoraReposicionEscapula: booleanField,
  mejoraRetraccion: booleanField,
  mejoraMulligan: booleanField,
  mejoraIsometricos: booleanField,
})

export type ShoulderData = z.infer<typeof shoulderDataSchema>
export type CervicalData = z.infer<typeof cervicalDataSchema>